#!/usr/bin/env python3
"""
Wizard Dashboard Backend API
Provides REST endpoints for wizard data.
"""


from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="Empathy Wizard API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

import time

# Calculate timestamps for realistic created/updated dates
NOW = int(time.time() * 1000)
DAY_MS = 24 * 60 * 60 * 1000

WIZARDS_DATA = [
    # ========================================
    # DOMAIN/INDUSTRY WIZARDS (16)
    # ========================================
    {
        "id": "healthcare",
        "name": "Healthcare Wizard",
        "description": "HIPAA-compliant clinical AI with automatic PHI de-identification",
        "icon": "🏥",
        "category": "domain",
        "industry": "healthcare",
        "compliance": ["HIPAA", "HITECH"],
        "classification": "SENSITIVE",
        "retentionDays": 90,
        "piiPatterns": ["mrn", "patient_id", "dob", "insurance_id", "npi", "cpt", "icd"],
        "empathyLevel": 3,
        "features": [
            "PHI de-identification",
            "Clinical decision support",
            "SBAR/SOAP notes",
            "Compliance verification",
        ],
        "tags": ["healthcare", "hipaa", "clinical", "medical", "phi"],
        "popularity": 95,
        "createdAt": NOW - 90 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "finance",
        "name": "Finance Wizard",
        "description": "SOX & PCI-DSS compliant banking and financial analysis",
        "icon": "💰",
        "category": "domain",
        "industry": "finance",
        "compliance": ["SOX", "PCI-DSS"],
        "classification": "SENSITIVE",
        "retentionDays": 2555,
        "piiPatterns": ["account_number", "routing_number", "tax_id", "swift", "iban"],
        "empathyLevel": 3,
        "features": [
            "Financial data protection",
            "Investment analysis",
            "Risk assessment",
            "7-year audit trail",
        ],
        "tags": ["finance", "sox", "pci-dss", "banking", "investment"],
        "popularity": 88,
        "createdAt": NOW - 85 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "legal",
        "name": "Legal Wizard",
        "description": "Attorney-client privilege with Fed. Rules 502 compliance",
        "icon": "⚖️",
        "category": "domain",
        "industry": "legal",
        "compliance": ["Rule 502"],
        "classification": "SENSITIVE",
        "retentionDays": 2555,
        "piiPatterns": ["case_number", "docket_number", "client_id", "matter_id", "bar_number"],
        "empathyLevel": 3,
        "features": [
            "Attorney-client privilege",
            "Legal research",
            "Contract analysis",
            "Case management",
        ],
        "tags": ["legal", "law", "compliance", "contracts", "litigation"],
        "popularity": 76,
        "createdAt": NOW - 80 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "education",
        "name": "Education Wizard",
        "description": "FERPA-compliant academic support and student privacy",
        "icon": "🎓",
        "category": "domain",
        "industry": "education",
        "compliance": ["FERPA"],
        "classification": "SENSITIVE",
        "retentionDays": 1825,
        "piiPatterns": [
            "student_id",
            "transcript_id",
            "grade_record",
            "enrollment",
            "financial_aid",
        ],
        "empathyLevel": 3,
        "features": [
            "Student privacy protection",
            "Academic planning",
            "Curriculum design",
            "IRB guidance",
        ],
        "tags": ["education", "ferpa", "academic", "students", "university"],
        "popularity": 82,
        "createdAt": NOW - 75 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "customer_support",
        "name": "Customer Support Wizard",
        "description": "Privacy-compliant help desk with Level 4 anticipatory empathy",
        "icon": "🤝",
        "category": "domain",
        "industry": "customer_support",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 730,
        "piiPatterns": ["customer_id", "ticket_number", "order_number", "account_number"],
        "empathyLevel": 4,
        "features": [
            "Ticket tracking",
            "Customer PII protection",
            "Anticipatory support",
            "Service excellence",
        ],
        "tags": ["support", "customer-service", "help-desk", "tickets"],
        "popularity": 85,
        "createdAt": NOW - 70 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "hr",
        "name": "HR Wizard",
        "description": "Employee privacy compliant with EEOC guidelines",
        "icon": "👥",
        "category": "domain",
        "industry": "hr",
        "compliance": ["EEOC"],
        "classification": "SENSITIVE",
        "retentionDays": 2555,
        "piiPatterns": ["employee_id", "salary", "compensation", "benefits", "performance_review"],
        "empathyLevel": 3,
        "features": [
            "Employee data protection",
            "Recruiting support",
            "HR compliance",
            "Performance management",
        ],
        "tags": ["hr", "human-resources", "recruiting", "employees"],
        "popularity": 78,
        "createdAt": NOW - 68 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "sales",
        "name": "Sales Wizard",
        "description": "CRM privacy compliant with Level 4 sales forecasting",
        "icon": "📊",
        "category": "domain",
        "industry": "sales",
        "compliance": ["CAN-SPAM", "GDPR"],
        "classification": "INTERNAL",
        "retentionDays": 1095,
        "piiPatterns": ["customer_id", "lead_id", "opportunity_id", "account_number"],
        "empathyLevel": 4,
        "features": [
            "CRM data protection",
            "Sales forecasting",
            "Pipeline analysis",
            "Campaign management",
        ],
        "tags": ["sales", "crm", "forecasting", "pipeline"],
        "popularity": 81,
        "createdAt": NOW - 65 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "real_estate",
        "name": "Real Estate Wizard",
        "description": "Property data privacy with Fair Housing Act compliance",
        "icon": "🏠",
        "category": "domain",
        "industry": "real_estate",
        "compliance": ["Fair Housing"],
        "classification": "INTERNAL",
        "retentionDays": 2555,
        "piiPatterns": [
            "mls_number",
            "parcel_id",
            "property_address",
            "client_id",
            "transaction_id",
        ],
        "empathyLevel": 3,
        "features": [
            "MLS data protection",
            "Market analysis",
            "Transaction support",
            "Property valuation",
        ],
        "tags": ["real-estate", "property", "mls", "housing"],
        "popularity": 72,
        "createdAt": NOW - 62 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "insurance",
        "name": "Insurance Wizard",
        "description": "Policy data privacy with state insurance regulations",
        "icon": "🛡️",
        "category": "domain",
        "industry": "insurance",
        "compliance": ["State Insurance Regs"],
        "classification": "SENSITIVE",
        "retentionDays": 2555,
        "piiPatterns": [
            "policy_number",
            "claim_number",
            "policyholder_id",
            "driver_license",
            "vin",
        ],
        "empathyLevel": 3,
        "features": [
            "Policyholder protection",
            "Claims support",
            "Underwriting assistance",
            "Risk analysis",
        ],
        "tags": ["insurance", "claims", "policy", "underwriting"],
        "popularity": 74,
        "createdAt": NOW - 60 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "accounting",
        "name": "Accounting Wizard",
        "description": "SOX/IRS compliant financial accounting and tax support",
        "icon": "🧮",
        "category": "domain",
        "industry": "accounting",
        "compliance": ["SOX", "IRS"],
        "classification": "SENSITIVE",
        "retentionDays": 2555,
        "piiPatterns": [
            "tax_id",
            "account_number",
            "bank_account",
            "routing_number",
            "financial_statement",
        ],
        "empathyLevel": 3,
        "features": [
            "Financial data protection",
            "Tax compliance",
            "Audit support",
            "GAAP guidance",
        ],
        "tags": ["accounting", "tax", "audit", "gaap"],
        "popularity": 77,
        "createdAt": NOW - 58 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "research",
        "name": "Research Wizard",
        "description": "IRB-compliant academic research with participant protection",
        "icon": "🔬",
        "category": "domain",
        "industry": "research",
        "compliance": ["IRB", "HIPAA"],
        "classification": "SENSITIVE",
        "retentionDays": 2555,
        "piiPatterns": ["participant_id", "subject_id", "protocol_number", "grant_id"],
        "empathyLevel": 3,
        "features": [
            "Participant protection",
            "IRB compliance",
            "Grant support",
            "Research methodology",
        ],
        "tags": ["research", "irb", "academic", "grants"],
        "popularity": 70,
        "createdAt": NOW - 56 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "government",
        "name": "Government Wizard",
        "description": "FISMA-compliant public sector with Privacy Act protection",
        "icon": "🏛️",
        "category": "domain",
        "industry": "government",
        "compliance": ["FISMA", "Privacy Act", "FedRAMP"],
        "classification": "SENSITIVE",
        "retentionDays": 2555,
        "piiPatterns": ["agency_id", "case_number", "permit_number", "license_number"],
        "empathyLevel": 3,
        "features": [
            "Citizen data protection",
            "Regulatory compliance",
            "Policy analysis",
            "NIST framework",
        ],
        "tags": ["government", "fisma", "public-sector", "fedramp"],
        "popularity": 68,
        "createdAt": NOW - 54 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "retail",
        "name": "Retail Wizard",
        "description": "PCI-DSS e-commerce with Level 4 demand forecasting",
        "icon": "🛒",
        "category": "domain",
        "industry": "retail",
        "compliance": ["PCI-DSS", "GDPR"],
        "classification": "SENSITIVE",
        "retentionDays": 730,
        "piiPatterns": ["customer_id", "order_number", "tracking_number", "loyalty_id"],
        "empathyLevel": 4,
        "features": [
            "Payment data protection",
            "Demand forecasting",
            "Inventory optimization",
            "Customer insights",
        ],
        "tags": ["retail", "e-commerce", "pci-dss", "forecasting"],
        "popularity": 80,
        "createdAt": NOW - 52 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "manufacturing",
        "name": "Manufacturing Wizard",
        "description": "Production data privacy with ISO standards compliance",
        "icon": "🏭",
        "category": "domain",
        "industry": "manufacturing",
        "compliance": ["ISO Standards"],
        "classification": "INTERNAL",
        "retentionDays": 1825,
        "piiPatterns": ["employee_id", "part_number", "serial_number", "batch_number"],
        "empathyLevel": 3,
        "features": [
            "Proprietary data protection",
            "Production optimization",
            "Quality control",
            "Six Sigma support",
        ],
        "tags": ["manufacturing", "production", "quality", "iso"],
        "popularity": 69,
        "createdAt": NOW - 50 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "logistics",
        "name": "Logistics Wizard",
        "description": "Shipment data privacy with transportation security",
        "icon": "🚚",
        "category": "domain",
        "industry": "logistics",
        "compliance": ["Transportation Security"],
        "classification": "INTERNAL",
        "retentionDays": 730,
        "piiPatterns": ["tracking_number", "shipment_id", "customer_id", "order_number"],
        "empathyLevel": 3,
        "features": [
            "Shipment data protection",
            "Route optimization",
            "Supply chain support",
            "Delivery tracking",
        ],
        "tags": ["logistics", "shipping", "supply-chain", "routing"],
        "popularity": 71,
        "createdAt": NOW - 48 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "technology",
        "name": "Technology Wizard",
        "description": "IT security compliant with SOC2 & ISO 27001",
        "icon": "💻",
        "category": "domain",
        "industry": "technology",
        "compliance": ["SOC2", "ISO 27001", "NIST"],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": ["api_key", "access_token", "ssh_key", "database_credential", "ip_address"],
        "empathyLevel": 3,
        "features": [
            "Infrastructure protection",
            "Enhanced secrets detection",
            "DevOps support",
            "Security best practices",
        ],
        "tags": ["technology", "devops", "soc2", "security"],
        "popularity": 84,
        "createdAt": NOW - 46 * DAY_MS,
        "updatedAt": NOW,
    },
    # ========================================
    # SOFTWARE DEVELOPMENT WIZARDS (16)
    # ========================================
    {
        "id": "debugging",
        "name": "Debugging Wizard",
        "description": "Production bug analysis with Level 4 pattern recognition",
        "icon": "🐛",
        "category": "software",
        "useCase": "debugging",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": ["email", "ip_address"],
        "empathyLevel": 4,
        "features": [
            "Root cause analysis",
            "Error pattern detection",
            "Stack trace analysis",
            "Bug prediction",
        ],
        "tags": ["debugging", "errors", "bugs", "troubleshooting"],
        "popularity": 92,
        "createdAt": NOW - 70 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "testing",
        "name": "Testing Wizard",
        "description": "Test coverage analysis and quality assurance",
        "icon": "🧪",
        "category": "software",
        "useCase": "testing",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 4,
        "features": [
            "Coverage analysis",
            "Test prioritization",
            "Gap detection",
            "Flaky test identification",
        ],
        "tags": ["testing", "qa", "quality", "coverage"],
        "popularity": 89,
        "createdAt": NOW - 65 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "security_wizard",
        "name": "Security Wizard",
        "description": "SOC2 & ISO 27001 security analysis and threat modeling",
        "icon": "🔒",
        "category": "software",
        "useCase": "security",
        "compliance": ["SOC2", "ISO 27001"],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": ["api_key", "access_token", "ssh_key"],
        "empathyLevel": 4,
        "features": [
            "Vulnerability scanning",
            "Threat modeling",
            "Security best practices",
            "Compliance verification",
        ],
        "tags": ["security", "soc2", "iso27001", "vulnerabilities"],
        "popularity": 91,
        "createdAt": NOW - 60 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "documentation",
        "name": "Documentation Wizard",
        "description": "Knowledge capture and documentation generation",
        "icon": "📝",
        "category": "software",
        "useCase": "documentation",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 3,
        "features": [
            "Auto-documentation",
            "Gap detection",
            "Knowledge transfer",
            "API docs generation",
        ],
        "tags": ["documentation", "docs", "knowledge", "api"],
        "popularity": 83,
        "createdAt": NOW - 58 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "performance_wizard",
        "name": "Performance Wizard",
        "description": "Performance profiling and optimization analysis",
        "icon": "⚡",
        "category": "software",
        "useCase": "performance",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 4,
        "features": [
            "Bottleneck detection",
            "Performance profiling",
            "Optimization suggestions",
            "Resource analysis",
        ],
        "tags": ["performance", "optimization", "profiling", "speed"],
        "popularity": 87,
        "createdAt": NOW - 56 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "refactoring",
        "name": "Refactoring Wizard",
        "description": "Code quality improvement and smell detection",
        "icon": "♻️",
        "category": "software",
        "useCase": "code_quality",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 3,
        "features": [
            "Code smell detection",
            "Refactoring suggestions",
            "Quality metrics",
            "Technical debt analysis",
        ],
        "tags": ["refactoring", "code-quality", "clean-code", "technical-debt"],
        "popularity": 79,
        "createdAt": NOW - 54 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "database",
        "name": "Database Wizard",
        "description": "Database design and query optimization",
        "icon": "🗄️",
        "category": "software",
        "useCase": "database",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": ["database_credential"],
        "empathyLevel": 3,
        "features": [
            "Schema design",
            "Query optimization",
            "Index recommendations",
            "Migration support",
        ],
        "tags": ["database", "sql", "optimization", "schema"],
        "popularity": 75,
        "createdAt": NOW - 52 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "api_wizard",
        "name": "API Wizard",
        "description": "REST/GraphQL API design and best practices",
        "icon": "🔌",
        "category": "software",
        "useCase": "api_design",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": ["api_key"],
        "empathyLevel": 3,
        "features": [
            "API design patterns",
            "REST best practices",
            "GraphQL support",
            "Versioning strategies",
        ],
        "tags": ["api", "rest", "graphql", "design"],
        "popularity": 82,
        "createdAt": NOW - 50 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "compliance_wizard",
        "name": "Compliance Wizard",
        "description": "GDPR, SOC2, and HIPAA compliance guidance",
        "icon": "📋",
        "category": "software",
        "useCase": "compliance",
        "compliance": ["GDPR", "SOC2", "HIPAA"],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 4,
        "features": ["Compliance checking", "GDPR support", "SOC2 guidance", "Audit preparation"],
        "tags": ["compliance", "gdpr", "soc2", "audit"],
        "popularity": 73,
        "createdAt": NOW - 48 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "monitoring",
        "name": "Monitoring Wizard",
        "description": "Observability, metrics, and SLO tracking",
        "icon": "📊",
        "category": "software",
        "useCase": "monitoring",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 4,
        "features": [
            "Metrics design",
            "Alerting strategies",
            "SLO/SLI definition",
            "Dashboard creation",
        ],
        "tags": ["monitoring", "observability", "metrics", "slo"],
        "popularity": 80,
        "createdAt": NOW - 46 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "devops",
        "name": "DevOps Wizard",
        "description": "CI/CD pipeline design and automation",
        "icon": "🚀",
        "category": "software",
        "useCase": "devops",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": ["ssh_key", "access_token"],
        "empathyLevel": 3,
        "features": [
            "CI/CD design",
            "Pipeline automation",
            "Infrastructure as code",
            "Deployment strategies",
        ],
        "tags": ["devops", "ci-cd", "automation", "deployment"],
        "popularity": 86,
        "createdAt": NOW - 44 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "accessibility",
        "name": "Accessibility Wizard",
        "description": "WCAG compliance and inclusive design",
        "icon": "♿",
        "category": "software",
        "useCase": "accessibility",
        "compliance": ["WCAG", "Section 508"],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 3,
        "features": [
            "WCAG compliance",
            "A11y testing",
            "Screen reader support",
            "Inclusive design",
        ],
        "tags": ["accessibility", "a11y", "wcag", "inclusive"],
        "popularity": 67,
        "createdAt": NOW - 42 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "localization",
        "name": "Localization Wizard",
        "description": "i18n/l10n and cultural adaptation",
        "icon": "🌍",
        "category": "software",
        "useCase": "localization",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 3,
        "features": [
            "Translation support",
            "Cultural adaptation",
            "Date/time formatting",
            "RTL languages",
        ],
        "tags": ["i18n", "l10n", "translation", "localization"],
        "popularity": 65,
        "createdAt": NOW - 40 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "design_review",
        "name": "Design Review Wizard",
        "description": "Architecture review and trade-off analysis",
        "icon": "🎨",
        "category": "software",
        "useCase": "architecture",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 5,
        "features": [
            "Architecture review",
            "Trade-off analysis",
            "ADR generation",
            "Pattern recommendations",
        ],
        "tags": ["architecture", "design", "patterns", "adr"],
        "popularity": 78,
        "createdAt": NOW - 38 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "onboarding",
        "name": "Onboarding Wizard",
        "description": "Team onboarding and knowledge transfer",
        "icon": "👋",
        "category": "software",
        "useCase": "onboarding",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 3,
        "features": [
            "Onboarding guides",
            "Setup automation",
            "Knowledge transfer",
            "Ramp-up tracking",
        ],
        "tags": ["onboarding", "team", "knowledge-transfer", "training"],
        "popularity": 70,
        "createdAt": NOW - 36 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "retrospective",
        "name": "Retrospective Wizard",
        "description": "Team retrospectives with Level 5 transformative insights",
        "icon": "🔄",
        "category": "software",
        "useCase": "team_process",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 5,
        "features": [
            "Retrospective facilitation",
            "Pattern extraction",
            "Improvement tracking",
            "Team insights",
        ],
        "tags": ["retrospective", "agile", "team", "improvement"],
        "popularity": 72,
        "createdAt": NOW - 34 * DAY_MS,
        "updatedAt": NOW,
    },
    # ========================================
    # AI & ENGINEERING WIZARDS (12)
    # ========================================
    {
        "id": "multi_model",
        "name": "Multi-Model Wizard",
        "description": "Level 4 anticipatory multi-model coordination",
        "icon": "🤖",
        "category": "ai",
        "useCase": "ai_development",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 4,
        "features": [
            "Model coordination",
            "Cost prediction",
            "Fallback strategies",
            "Consistency analysis",
        ],
        "tags": ["ai", "multi-model", "coordination", "llm"],
        "popularity": 87,
        "createdAt": NOW - 55 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "rag_pattern",
        "name": "RAG Pattern Wizard",
        "description": "Retrieval-augmented generation optimization",
        "icon": "📚",
        "category": "ai",
        "useCase": "ai_development",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 4,
        "features": [
            "Retrieval optimization",
            "Chunk size analysis",
            "Reranking strategies",
            "Quality prediction",
        ],
        "tags": ["rag", "retrieval", "embeddings", "vector-db"],
        "popularity": 85,
        "createdAt": NOW - 50 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "ai_performance",
        "name": "AI Performance Wizard",
        "description": "Level 4 AI performance profiling and optimization",
        "icon": "⚡",
        "category": "ai",
        "useCase": "performance",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 4,
        "features": [
            "Inference optimization",
            "Latency prediction",
            "Token usage analysis",
            "Caching strategies",
        ],
        "tags": ["performance", "optimization", "ai", "latency"],
        "popularity": 90,
        "createdAt": NOW - 45 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "ai_collaboration",
        "name": "AI Collaboration Wizard",
        "description": "Multi-agent collaboration and orchestration",
        "icon": "🤝",
        "category": "ai",
        "useCase": "ai_development",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 4,
        "features": [
            "Agent coordination",
            "Task delegation",
            "Conflict resolution",
            "Shared state management",
        ],
        "tags": ["ai", "multi-agent", "collaboration", "orchestration"],
        "popularity": 83,
        "createdAt": NOW - 43 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "advanced_debugging_ai",
        "name": "Advanced Debugging Wizard",
        "description": "AI-powered debugging with pattern prediction",
        "icon": "🔍",
        "category": "ai",
        "useCase": "debugging",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 4,
        "features": [
            "AI bug detection",
            "Pattern prediction",
            "Anomaly detection",
            "Root cause AI",
        ],
        "tags": ["debugging", "ai", "ml", "prediction"],
        "popularity": 86,
        "createdAt": NOW - 41 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "agent_orchestration",
        "name": "Agent Orchestration Wizard",
        "description": "Complex agent workflow orchestration",
        "icon": "🎭",
        "category": "ai",
        "useCase": "ai_development",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 4,
        "features": [
            "Workflow design",
            "Failure handling",
            "State management",
            "Orchestration patterns",
        ],
        "tags": ["orchestration", "agents", "workflow", "ai"],
        "popularity": 81,
        "createdAt": NOW - 39 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "enhanced_testing_ai",
        "name": "Enhanced Testing Wizard",
        "description": "AI-powered test generation and optimization",
        "icon": "🧬",
        "category": "ai",
        "useCase": "testing",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 4,
        "features": [
            "AI test generation",
            "Flaky test prediction",
            "Test parallelization",
            "Smart test selection",
        ],
        "tags": ["testing", "ai", "test-generation", "optimization"],
        "popularity": 79,
        "createdAt": NOW - 37 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "ai_documentation",
        "name": "AI Documentation Wizard",
        "description": "AI component documentation and explanation",
        "icon": "📖",
        "category": "ai",
        "useCase": "documentation",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 4,
        "features": [
            "AI docs generation",
            "Model card creation",
            "Prompt documentation",
            "System diagrams",
        ],
        "tags": ["documentation", "ai", "model-cards", "explainability"],
        "popularity": 76,
        "createdAt": NOW - 35 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "prompt_engineering",
        "name": "Prompt Engineering Wizard",
        "description": "Prompt optimization and version control",
        "icon": "✍️",
        "category": "ai",
        "useCase": "ai_development",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 4,
        "features": ["Prompt optimization", "Version control", "A/B testing", "Pattern libraries"],
        "tags": ["prompts", "llm", "optimization", "versioning"],
        "popularity": 88,
        "createdAt": NOW - 33 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "ai_context",
        "name": "AI Context Wizard",
        "description": "Context window management and optimization",
        "icon": "📋",
        "category": "ai",
        "useCase": "ai_development",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 4,
        "features": [
            "Context optimization",
            "Token management",
            "Summarization strategies",
            "Window planning",
        ],
        "tags": ["context", "tokens", "llm", "optimization"],
        "popularity": 82,
        "createdAt": NOW - 31 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "security_analysis_ai",
        "name": "AI Security Analysis Wizard",
        "description": "AI-specific security analysis and protection",
        "icon": "🛡️",
        "category": "ai",
        "useCase": "security",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": ["api_key"],
        "empathyLevel": 4,
        "features": [
            "Prompt injection detection",
            "PII protection",
            "Rate limiting",
            "Security best practices",
        ],
        "tags": ["security", "ai", "prompt-injection", "protection"],
        "popularity": 84,
        "createdAt": NOW - 29 * DAY_MS,
        "updatedAt": NOW,
    },
    {
        "id": "ai_testing",
        "name": "AI Testing Wizard",
        "description": "LLM output validation and quality assurance",
        "icon": "🎯",
        "category": "ai",
        "useCase": "testing",
        "compliance": [],
        "classification": "INTERNAL",
        "retentionDays": 365,
        "piiPatterns": [],
        "empathyLevel": 4,
        "features": [
            "Output validation",
            "Quality metrics",
            "Regression testing",
            "Evaluation frameworks",
        ],
        "tags": ["testing", "ai", "llm", "validation"],
        "popularity": 80,
        "createdAt": NOW - 27 * DAY_MS,
        "updatedAt": NOW,
    },
]


@app.get("/api/wizards")
async def get_wizards():
    return {"wizards": WIZARDS_DATA, "total": len(WIZARDS_DATA)}


@app.get("/api/wizards/{wizard_id}")
async def get_wizard(wizard_id: str):
    wizard = next((w for w in WIZARDS_DATA if w["id"] == wizard_id), None)
    if not wizard:
        raise HTTPException(status_code=404, detail="Wizard not found")
    return wizard


if __name__ == "__main__":
    import uvicorn

    print("🧙 Starting API at http://localhost:8000")
    uvicorn.run(app, host="0.0.0.0", port=8000)
