# Funding options for Empathy Framework
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-supporter-button-in-your-repository

custom: ["https://deepstudyai.com", "mailto:sales@deepstudyai.com?subject=Empathy%20Framework%20Support"]
