# Label configuration for actions/labeler
# See: https://github.com/actions/labeler

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**/*'
          - '*.md'
          - 'mkdocs.yml'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**/*'

core:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/empathy_os/**/*'
          - 'empathy_llm_toolkit/**/*'

plugins:
  - changed-files:
      - any-glob-to-any-file:
          - 'empathy_software_plugin/**/*'
          - 'empathy_healthcare_plugin/**/*'

wizards:
  - changed-files:
      - any-glob-to-any-file:
          - 'coach_wizards/**/*'
          - 'wizards/**/*'

cli:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/empathy_os/cli*.py'
          - 'empathy_llm_toolkit/cli/**/*'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**/*'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'pyproject.toml'
          - 'requirements*.txt'

security:
  - changed-files:
      - any-glob-to-any-file:
          - 'empathy_llm_toolkit/security/**/*'
          - '.bandit'
          - '.github/workflows/security.yml'

devcontainer:
  - changed-files:
      - any-glob-to-any-file:
          - '.devcontainer/**/*'
