# Label configuration for actions/labeler
# See: https://github.com/actions/labeler

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**/*'
          - '*.md'
          - 'mkdocs.yml'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**/*'

core:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/attune/**/*'
          - 'attune_llm/**/*'

plugins:
  - changed-files:
      - any-glob-to-any-file:
          - 'attune_software/**/*'
          - 'attune_healthcare/**/*'

wizards:
  - changed-files:
      - any-glob-to-any-file:
          - 'coach_wizards/**/*'
          - 'wizards/**/*'

cli:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/attune/cli*.py'
          - 'attune_llm/cli/**/*'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**/*'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'pyproject.toml'
          - 'requirements*.txt'

security:
  - changed-files:
      - any-glob-to-any-file:
          - 'attune_llm/security/**/*'
          - '.bandit'
          - '.github/workflows/security.yml'

devcontainer:
  - changed-files:
      - any-glob-to-any-file:
          - '.devcontainer/**/*'
