"""Test fixtures for patient_assessment wizard.

Auto-generated by Attune AI Test Generator
Provides common test data and mocks.
"""

from unittest.mock import MagicMock

import pytest


@pytest.fixture
def sample_patient_assessment_data():
    """Sample data for patient_assessment wizard."""
    return {
        "field1": "test value 1",
        "field2": "test value 2",
    }


@pytest.fixture
def mock_patient_assessment_dependencies():
    """Mock dependencies for patient_assessment wizard."""
    return {
        "database": MagicMock(),
        "api_client": MagicMock(),
    }
