"""Test fixtures for code_reviewer wizard.

Auto-generated by Attune AI Test Generator
Provides common test data and mocks.
"""

from unittest.mock import MagicMock

import pytest


@pytest.fixture
def sample_code_reviewer_data():
    """Sample data for code_reviewer wizard."""
    return {
        "field1": "test value 1",
        "field2": "test value 2",
    }


@pytest.fixture
def mock_code_reviewer_dependencies():
    """Mock dependencies for code_reviewer wizard."""
    return {
        "database": MagicMock(),
        "api_client": MagicMock(),
    }
