"""Test fixtures for test_e2e_wizard wizard.

Auto-generated by Empathy Framework Test Generator
Provides common test data and mocks.
"""

from unittest.mock import MagicMock

import pytest


@pytest.fixture
def sample_test_e2e_wizard_data():
    """Sample data for test_e2e_wizard wizard."""
    return {
        "field1": "test value 1",
        "field2": "test value 2",
    }


@pytest.fixture
def mock_test_e2e_wizard_dependencies():
    """Mock dependencies for test_e2e_wizard wizard."""
    return {
        "database": MagicMock(),
        "api_client": MagicMock(),
    }
