"""Behavioral tests for platform_utils.

Generated by LLM-enhanced test generation system.

Copyright 2026 Smart-AI-Memory
Licensed under Apache 2.0
"""

import os
from pathlib import Path
from unittest.mock import MagicMock, patch

from attune import platform_utils


class TestPlatformDetection:
    """Tests for platform detection functions."""

    def test_is_windows_when_on_windows(self):
        """Given Windows platform
        When is_windows() is called
        Then should return True
        """
        # Given
        with patch("platform.system", return_value="Windows"):
            # When
            result = platform_utils.is_windows()
            # Then
            assert result is True

    def test_is_windows_when_not_on_windows(self):
        """Given non-Windows platform
        When is_windows() is called
        Then should return False
        """
        # Given
        with patch("platform.system", return_value="Linux"):
            # When
            result = platform_utils.is_windows()
            # Then
            assert result is False

    def test_is_macos_when_on_macos(self):
        """Given macOS platform
        When is_macos() is called
        Then should return True
        """
        # Given
        with patch("platform.system", return_value="Darwin"):
            # When
            result = platform_utils.is_macos()
            # Then
            assert result is True

    def test_is_macos_when_not_on_macos(self):
        """Given non-macOS platform
        When is_macos() is called
        Then should return False
        """
        # Given
        with patch("platform.system", return_value="Windows"):
            # When
            result = platform_utils.is_macos()
            # Then
            assert result is False

    def test_is_linux_when_on_linux(self):
        """Given Linux platform
        When is_linux() is called
        Then should return True
        """
        # Given
        with patch("platform.system", return_value="Linux"):
            # When
            result = platform_utils.is_linux()
            # Then
            assert result is True

    def test_is_linux_when_not_on_linux(self):
        """Given non-Linux platform
        When is_linux() is called
        Then should return False
        """
        # Given
        with patch("platform.system", return_value="Darwin"):
            # When
            result = platform_utils.is_linux()
            # Then
            assert result is False


class TestGetDefaultLogDir:
    """Tests for get_default_log_dir function."""

    def test_get_default_log_dir_on_windows_with_appdata(self):
        """Given Windows platform with APPDATA environment variable
        When get_default_log_dir() is called
        Then should return %APPDATA%/empathy/logs
        """
        # Given
        with patch("attune.platform_utils.is_windows", return_value=True):
            with patch.dict(os.environ, {"APPDATA": "C:\\Users\\Test\\AppData\\Roaming"}):
                # When
                result = platform_utils.get_default_log_dir()
                # Then - use parts to compare platform-independently
                assert result.parts[-2:] == ("empathy", "logs")
                assert "AppData" in str(result)

    def test_get_default_log_dir_on_windows_without_appdata(self):
        """Given Windows platform without APPDATA environment variable
        When get_default_log_dir() is called
        Then should return home directory with empathy/logs
        """
        # Given
        with patch("attune.platform_utils.is_windows", return_value=True):
            with patch.dict(os.environ, {}, clear=True):
                with patch("os.path.expanduser", return_value="/home/user"):
                    # When
                    result = platform_utils.get_default_log_dir()
                    # Then
                    assert result == Path("/home/user/empathy/logs")

    def test_get_default_log_dir_on_macos(self):
        """Given macOS platform
        When get_default_log_dir() is called
        Then should return ~/Library/Logs/empathy
        """
        # Given
        with patch("attune.platform_utils.is_windows", return_value=False):
            with patch("attune.platform_utils.is_macos", return_value=True):
                with patch("pathlib.Path.home", return_value=Path("/Users/test")):
                    # When
                    result = platform_utils.get_default_log_dir()
                    # Then
                    assert result == Path("/Users/test/Library/Logs/empathy")

    def test_get_default_log_dir_on_linux_with_writable_var_log(self):
        """Given Linux platform with writable /var/log
        When get_default_log_dir() is called
        Then should return /var/log/empathy
        """
        # Given
        with patch("attune.platform_utils.is_windows", return_value=False):
            with patch("attune.platform_utils.is_macos", return_value=False):
                with patch("pathlib.Path.exists", return_value=True):
                    # When
                    result = platform_utils.get_default_log_dir()
                    # Then
                    assert result == Path("/var/log/empathy")

    def test_get_default_log_dir_on_linux_with_writable_parent(self):
        """Given Linux platform with non-existing /var/log/empathy but writable parent
        When get_default_log_dir() is called
        Then should return a valid log directory
        """
        # Given
        with patch("attune.platform_utils.is_windows", return_value=False):
            with patch("attune.platform_utils.is_macos", return_value=False):
                with patch("os.access", return_value=True):
                    # When
                    result = platform_utils.get_default_log_dir()
                    # Then - should return a valid path
                    assert isinstance(result, Path)
                    assert "empathy" in str(result)

    def test_get_default_log_dir_on_linux_fallback_to_user_directory(self):
        """Given Linux platform with non-writable /var/log
        When get_default_log_dir() is called
        Then should return ~/.local/share/empathy/logs
        """
        # Given
        with patch("attune.platform_utils.is_windows", return_value=False):
            with patch("attune.platform_utils.is_macos", return_value=False):
                with patch("os.access", return_value=False):
                    with patch("pathlib.Path.home", return_value=Path("/home/test")):
                        # When
                        result = platform_utils.get_default_log_dir()
                        # Then - should use home directory path
                        assert "home" in str(result) or ".local" in str(result)


class TestGetDefaultDataDir:
    """Tests for get_default_data_dir function."""

    def test_get_default_data_dir_on_windows_with_appdata(self):
        """Given Windows platform with APPDATA environment variable
        When get_default_data_dir() is called
        Then should return %APPDATA%/empathy
        """
        # Given
        with patch("attune.platform_utils.is_windows", return_value=True):
            with patch.dict(os.environ, {"APPDATA": "C:\\Users\\Test\\AppData\\Roaming"}):
                # When
                result = platform_utils.get_default_data_dir()
                # Then - use parts to compare platform-independently
                assert result.parts[-1] == "empathy"
                assert "AppData" in str(result)

    def test_get_default_data_dir_on_windows_without_appdata(self):
        """Given Windows platform without APPDATA environment variable
        When get_default_data_dir() is called
        Then should return home directory with empathy
        """
        # Given
        with patch("attune.platform_utils.is_windows", return_value=True):
            with patch.dict(os.environ, {}, clear=True):
                with patch("os.path.expanduser", return_value="/home/user"):
                    # When
                    result = platform_utils.get_default_data_dir()
                    # Then
                    assert result == Path("/home/user/empathy")

    def test_get_default_data_dir_on_macos(self):
        """Given macOS platform
        When get_default_data_dir() is called
        Then should return ~/Library/Application Support/empathy
        """
        # Given
        with patch("attune.platform_utils.is_windows", return_value=False):
            with patch("attune.platform_utils.is_macos", return_value=True):
                with patch("pathlib.Path.home", return_value=Path("/Users/test")):
                    # When
                    result = platform_utils.get_default_data_dir()
                    # Then
                    assert result == Path("/Users/test/Library/Application Support/empathy")

    def test_get_default_data_dir_on_linux_with_xdg_data_home(self):
        """Given Linux platform with XDG_DATA_HOME set
        When get_default_data_dir() is called
        Then should return $XDG_DATA_HOME/empathy
        """
        # Given
        with patch("attune.platform_utils.is_windows", return_value=False):
            with patch("attune.platform_utils.is_macos", return_value=False):
                with patch.dict(os.environ, {"XDG_DATA_HOME": "/custom/data"}):
                    # When
                    result = platform_utils.get_default_data_dir()
                    # Then
                    assert result == Path("/custom/data/empathy")

    def test_get_default_data_dir_on_linux_without_xdg_data_home(self):
        """Given Linux platform without XDG_DATA_HOME
        When get_default_data_dir() is called
        Then should return ~/.local/share/empathy
        """
        # Given
        with patch("attune.platform_utils.is_windows", return_value=False):
            with patch("attune.platform_utils.is_macos", return_value=False):
                with patch.dict(os.environ, {}, clear=True):
                    with patch("pathlib.Path.home", return_value=Path("/home/test")):
                        # When
                        result = platform_utils.get_default_data_dir()
                        # Then
                        assert result == Path("/home/test/.local/share/empathy")


class TestGetDefaultConfigDir:
    """Tests for get_default_config_dir function."""

    def test_get_default_config_dir_on_windows_with_appdata(self):
        """Given Windows platform with APPDATA environment variable
        When get_default_config_dir() is called
        Then should return %APPDATA%/empathy
        """
        # Given
        with patch("attune.platform_utils.is_windows", return_value=True):
            with patch.dict(os.environ, {"APPDATA": "C:\\Users\\Test\\AppData\\Roaming"}):
                # When
                result = platform_utils.get_default_config_dir()
                # Then - use parts to compare platform-independently
                assert result.parts[-1] == "empathy"
                assert "AppData" in str(result)

    def test_get_default_config_dir_on_windows_without_appdata(self):
        """Given Windows platform without APPDATA environment variable
        When get_default_config_dir() is called
        Then should return home directory with empathy
        """
        # Given
        with patch("attune.platform_utils.is_windows", return_value=True):
            with patch.dict(os.environ, {}, clear=True):
                with patch("os.path.expanduser", return_value="/home/user"):
                    # When
                    result = platform_utils.get_default_config_dir()
                    # Then
                    assert result == Path("/home/user/empathy")

    def test_get_default_config_dir_on_macos(self):
        """Given macOS platform
        When get_default_config_dir() is called
        Then should return ~/Library/Preferences/empathy
        """
        # Given
        with patch("attune.platform_utils.is_windows", return_value=False):
            with patch("attune.platform_utils.is_macos", return_value=True):
                with patch("pathlib.Path.home", return_value=Path("/Users/test")):
                    # When
                    result = platform_utils.get_default_config_dir()
                    # Then
                    assert result == Path("/Users/test/Library/Preferences/empathy")

    def test_get_default_config_dir_on_linux_with_xdg_config_home(self):
        """Given Linux platform with XDG_CONFIG_HOME set
        When get_default_config_dir() is called
        Then should return $XDG_CONFIG_HOME/empathy
        """
        # Given
        with patch("attune.platform_utils.is_windows", return_value=False):
            with patch("attune.platform_utils.is_macos", return_value=False):
                with patch.dict(os.environ, {"XDG_CONFIG_HOME": "/custom/config"}):
                    # When
                    result = platform_utils.get_default_config_dir()
                    # Then
                    assert result == Path("/custom/config/empathy")

    def test_get_default_config_dir_on_linux_without_xdg_config_home(self):
        """Given Linux platform without XDG_CONFIG_HOME
        When get_default_config_dir() is called
        Then should return ~/.config/empathy
        """
        # Given
        with patch("attune.platform_utils.is_windows", return_value=False):
            with patch("attune.platform_utils.is_macos", return_value=False):
                with patch.dict(os.environ, {}, clear=True):
                    with patch("pathlib.Path.home", return_value=Path("/home/test")):
                        # When
                        result = platform_utils.get_default_config_dir()
                        # Then
                        assert result == Path("/home/test/.config/empathy")


class TestGetDefaultCacheDir:
    """Tests for get_default_cache_dir function."""

    def test_get_default_cache_dir_on_windows_with_localappdata(self):
        """Given Windows platform with LOCALAPPDATA environment variable
        When get_default_cache_dir() is called
        Then should return %LOCALAPPDATA%/empathy/cache
        """
        # Given
        with patch("attune.platform_utils.is_windows", return_value=True):
            with patch.dict(os.environ, {"LOCALAPPDATA": r"C:\Users\Test\AppData\Local"}):
                # When
                result = platform_utils.get_default_cache_dir()
                # Then - use parts to compare platform-independently
                assert result.parts[-2:] == ("empathy", "cache")
                assert "AppData" in str(result)
